-- AlterTable
ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "variantId" TEXT,
ADD COLUMN IF NOT EXISTS "variantTitle" TEXT,
ADD COLUMN IF NOT EXISTS "size" TEXT;

-- AlterTable
ALTER TABLE "Return" ADD COLUMN IF NOT EXISTS "variantTitle" TEXT,
ADD COLUMN IF NOT EXISTS "size" TEXT,
ADD COLUMN IF NOT EXISTS "title" TEXT;

-- AlterTable
ALTER TABLE "Exchange" ADD COLUMN IF NOT EXISTS "originalVariantTitle" TEXT,
ADD COLUMN IF NOT EXISTS "originalSize" TEXT,
ADD COLUMN IF NOT EXISTS "newVariantTitle" TEXT,
ADD COLUMN IF NOT EXISTS "newSize" TEXT;
